artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: D:\Satyam Projects\Chicken Disease\Training Images
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion